name: Build on release branch

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    name: pnpm build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'pnpm'

      - name: Enable pnpm (via Corepack)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
